import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/concatMap';
import 'rxjs/add/operator/mergeMap';
import * as filter from './filter';
export * from './interfaces';
export * from './exec';
export * from './spawn';
export * from './find';
export * from './diff';
export * from './readFile';
export * from './writeFile';
export * from './readdir';
export * from './link';
export * from './mkdir';
export * from './stat';
import * as tmp from './tmp';
export { tmp, filter };
export * from './exists';
export * from './unlink';
export * from './from';
export declare const readdir: (filepath: string) => Observable<string>;
